// DEVELOPMENT TEST 
### TEST FOR CONTACTS COLLECTION 
### Get all Contacts 
GET http://localhost:3000/contacts/

### Get contact by id
GET http://localhost:3000/contacts/

### Create new Contact 
POST http://localhost:3000/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Christopher",
    "lastName": "Adler",
    "email": "c.adler@mail.io",
    "favoriteColor": "crimson",
    "birthday": "1989-03-22"
}

### Update Contact 
PUT http://localhost:3000/contacts/
Content-Type: application/json

{
    "firstName": "Isabella",
    "lastName": "Bennett",
    "email": "i.bennett@webmail.net",
    "favoriteColor": "teal",
    "birthday": "1994-07-18"
}

### Delete Contact 
DELETE http://localhost:3000/contacts/


// PRODUCTION TEST 
### TEST FOR CONTACTS COLLECTION 
### Get all Contacts 
GET https://cse341-9e5j.onrender.com/contacts/

### Get contact by id
GET https://cse341-9e5j.onrender.com/contacts/

### Create new Contact 
POST https://cse341-9e5j.onrender.com/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Nathan",
    "lastName": "Crawford",
    "email": "n.crawford@email.io",
    "favoriteColor": "navy",
    "birthday": "1991-12-05"
}

### Update Contact 
PUT https://cse341-9e5j.onrender.com/contacts/
Content-Type: application/json

{
    "firstName": "Victoria",
    "lastName": "Donnelly",
    "email": "v.donnelly@mail.net",
    "favoriteColor": "coral",
    "birthday": "1993-06-14"
}

### Delete Contact 
DELETE https://cse341-9e5j.onrender.com/contacts/
