// DEVELOPMENT TEST 
### TEST FOR PRODUCTS COLLECTION 

### Get all Orders
GET http://localhost:3000/orders/

### Get a Single Order 
GET http://localhost:3000/orders/675a0d39354bb9678a73e6cf


### Create New Order
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

{
    "userId": "67510ca4b2e070c991a8348e", 
    "productIds": ["67510ce8b2e070c991a83496", "67510ce8b2e070c991a83497"],
    "orderDate": "2024-06-06", 
    "totalAmount": "3600.99", 
    "status": "Pending"
}


### Update Order
PUT http://localhost:3000/orders/67510d4bb2e070c991a834a0 HTTP/1.1
Content-Type: application/json

{
    "userId": "67510ca4b2e070c991a8348d", 
    "productIds": ["67510ce8b2e070c991a83496", "67510ce8b2e070c991a83497"],
    "orderDate": "2024-12-10", 
    "totalAmount": 3500.99, 
    "status": "Pending"
}

### Delete Order
DELETE http://localhost:3000/orders/:id HTTP/1.1

### Get Products for Order
GET http://localhost:3000/orders/products/67510d4bb2e070c991a834a0

### Get all Orders for a User
GET http://localhost:3000/orders/user/67510ca4b2e070c991a8348d


// Production TEST 
### TEST FOR PRODUCTS COLLECTION 

### Get all Orders
GET http://cse341-ecommerce.onrender.com/orders/

### Get a Single Order 
GET http://cse341-ecommerce.onrender.com/orders/675a0d39354bb9678a73e6cf


### Create New Order
POST http://cse341-ecommerce.onrender.com/orders HTTP/1.1
Content-Type: application/json

{
    "userId": "67510ca4b2e070c991a8348e", 
    "productIds": ["67510ce8b2e070c991a83496", "67510ce8b2e070c991a83497"],
    "orderDate": "2024-12-10", 
    "totalAmount": 3600.99, 
    "status": "Pending"
}


### Update Order
PUT http://cse341-ecommerce.onrender.com/orders/67510d4bb2e070c991a834a0 HTTP/1.1
Content-Type: application/json

{
    "userId": "67510ca4b2e070c991a8348d", 
    "productIds": ["67510ce8b2e070c991a83496", "67510ce8b2e070c991a83497"],
    "orderDate": "2024-12-10", 
    "totalAmount": 3500.99, 
    "status": "Pending"
}

### Delete Order
DELETE http://cse341-ecommerce.onrender.com/orders/:id HTTP/1.1

### Get Products for Order
GET http://cse341-ecommerce.onrender.com/orders/products/67510d4bb2e070c991a834a0

### Get all Orders for a User
GET http://cse341-ecommerce.onrender.com/orders/user/67510ca4b2e070c991a8348d

