// DEVELOPMENT TEST 
### TEST FOR PRODUCTS COLLECTION 
### Get all Products 
GET http://localhost:3000/products/

### Create new Product 
POST http://localhost:3000/products HTTP/1.1 
Content-Type: application/json

{
"name": "Smart Watch Series 8", 
"category": "Wearables", 
"description": "The latest Apple smartwatch with advanced health tracking.",
"price": 299.99, 
"stockQuantity": 75, 
"brand": "Apple", 
"rating": 4, 
"dateAdded": "2024-11-10", 
"isAvailable": true
}

### Update Product 
PUT http://localhost:3000/products/ HTTP/1.1 
Content-Type: application/json

{
"name": "Smart Watch Series 8", 
"category": "Wearables",
"description": "The latest Apple smartwatch with advanced health tracking.",
"price": 99.99, 
"stockQuantity":15, 
"brand": "Apple", 
"rating": 4, 
"dateAdded": "2024-11-10", 
"isAvailable": true
}

### Delete Product 
DELETE http://localhost:3000/products/ HTTP/1.1


// PRODUCTION TEST 
### TEST FOR PRODUCTS COLLECTION 
### Get all Products 
GET http://cse341-ecommerce.onrender.com/products/

### Create new Product 
POST http://cse341-ecommerce.onrender.com/products HTTP/1.1 
Content-Type: application/json

{
"name": "Smart Watch Series 8", 
"category": "Wearables", 
"description": "The latest Apple smartwatch with advanced health tracking.",
"price": 299.99, 
"stockQuantity": 75, 
"brand": "Apple", 
"rating": 4, 
"dateAdded": "2024-11-10", 
"isAvailable": true
}

### Update Product 
PUT http://cse341-ecommerce.onrender.com/products/ HTTP/1.1 
Content-Type: application/json

{
"name": "Smart Watch Series 8", 
"category": "Wearables",
"description": "The latest Apple smartwatch with advanced health tracking.",
"price": 99.99, 
"stockQuantity":15, 
"brand": "Apple", 
"rating": 4, 
"dateAdded": "2024-11-10", 
"isAvailable": true
}

### Delete Product 
DELETE http://cse341-ecommerce.onrender.com/products/ HTTP/1.1