// DEVELOPMENT TEST 
### TEST FOR REVIEWS COLLECTION 
### Get all Reviews 
GET http://localhost:3000/reviews/

### Create new Review 
POST http://localhost:3000/reviews HTTP/1.1 
Content-Type: application/json

{
    "productId": "67510ce8b2e070c991a8349a",
    "userId": "67510ca4b2e070c991a8348d",
    "rating": 5,
    "comment": "This product was amazing! Highly recommend it. Photos matches the products",
    "createdAt": "2024-12-01T14:00:00Z"
}


### Update Review 
PUT http://localhost:3000/reviews/ HTTP/1.1 
Content-Type: application/json

{
    "productId": "67510ce8b2e070c991a8349a",
    "userId": "67510ca4b2e070c991a8348d",
    "rating": 4,
    "comment": "This product was amazing! Highly recommend it. Photos matches the products",
    "createdAt": "2024-12-01T14:00:00Z"
}

### Delete Review 
DELETE http://localhost:3000/reviews/ HTTP/1.1


// PRODUCTION TEST 
### TEST FOR REVIEWS COLLECTION 
### Get all Reviews 
GET http:/cse341-ecommerce.onrender.com/reviews/

### Create new Review 
POST http:/cse341-ecommerce.onrender.com/reviews HTTP/1.1 
Content-Type: application/json

{
    "productId": "67510ce8b2e070c991a8349a",
    "userId": "67510ca4b2e070c991a8348d",
    "rating": 5,
    "comment": "This product was amazing! Highly recommend it. Photos matches the products",
    "createdAt": "2024-12-01T14:00:00Z"
}


### Update Review 
PUT http:/cse341-ecommerce.onrender.com/reviews/ HTTP/1.1 
Content-Type: application/json

{
    "productId": "67510ce8b2e070c991a8349a",
    "userId": "67510ca4b2e070c991a8348d",
    "rating": 4,
    "comment": "This product was amazing! Highly recommend it. Photos matches the products",
    "createdAt": "2024-12-01T14:00:00Z"
}

### Delete Review 
DELETE http:/cse341-ecommerce.onrender.com/reviews/ HTTP/1.1