// DEVELOPMENT TEST 
### TEST FOR USERS COLLECTION ### Get all user 
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/67510ca4b2e070c991a8348d

### Create new user
POST http://localhost:3000/users HTTP/1.1 
Content-Type: application/json

{
  "firstName": "Brandon",
  "lastName": "Hayes",
  "email": "b.hayes@mailpro.io",
  "passwordHash": "",
  "address": "512 Grove Street, Phoenix, AZ",
  "createdAt": "2024-11-12"
}

### Update user
PUT http://localhost:3000/users/7548859eeb7864d567c3a69 HTTP/1.1 
Content-Type: application/json

{
  "firstName": "Rachel",
  "lastName": "Foster",
  "email": "r.foster@webmail.io",
  "passwordHash": "",
  "address": "789 Maple Avenue, Houston, TX",
  "createdAt": "2024-11-11"
}

### Delete user
DELETE http://localhost:3000/users/7548859eeb7864d567c3a69 HTTP/1.1